forall-errors.chpl:11: In function 'main':
forall-errors.chpl:12: error: call to throwing function throwingFn without try or try! (strict mode)
forall-errors.chpl:4: note: throwing function throwingFn defined here
